#!/bin/sh
set -eu
case "${1:-}" in
  attach|stop) exec python3 /usr/local/lib/l4d2-supervisor.py "$1" ;;
  status) [ "${2:-}" = "--json" ] || exit 64; exec python3 /usr/local/lib/l4d2-supervisor.py status ;;
  *) exit 64 ;;
esac
