import {useState} from 'react'
import {Activity, Box, CalendarClock, ChevronRight, CircleStop, Database, Gauge, Map, Play, Plus, RefreshCw, Server, Settings, ShieldCheck, TerminalSquare, Users} from 'lucide-react'
import '../styles/app.css'

export type Instance={id:string;name:string;actual_state:string;game_port:number;start_map:string;game_mode:string;max_players:number;players:number;cpu:number;memory:number}
type Props={initialInstances?:Instance[];onAction?:(id:string,action:string)=>void}
const demo:Instance[]=[{id:'1',name:'深夜战役',actual_state:'running',game_port:27015,start_map:'c2m1_highway',game_mode:'coop',max_players:8,players:4,cpu:31,memory:2.4},{id:'2',name:'专家写实',actual_state:'stopped',game_port:27025,start_map:'c8m1_apartment',game_mode:'realism',max_players:4,players:0,cpu:0,memory:0}]

export function App({initialInstances=demo,onAction=()=>{}}:Props){const[instances]=useState(initialInstances);const[pending,setPending]=useState<Instance|null>(null);const running=instances.filter(x=>x.actual_state==='running').length;return <div className="shell">
  <aside><div className="brand"><span className="hazard">L4D</span><div><b>CONTROL</b><small>NODE / LOCAL-01</small></div></div><nav aria-label="主导航"><a className="active"><Gauge/>总览</a><a><Server/>实例</a><a><Box/>内容仓库</a><a><CalendarClock/>计划任务</a><a><TerminalSquare/>作业日志</a></nav><div className="aside-foot"><a><Settings/>系统设置</a><div className="node"><i></i><span>控制节点在线<small>Docker API 正常</small></span></div></div></aside>
  <main><header><div><p className="eyebrow">OPERATIONS / OVERVIEW</p><h1>服务器作战室</h1><p>管理游戏进程、内容部署与计划维护。</p></div><div className="operator"><span className="pulse"></span><div><b>管理员</b><small>安全会话 · 23h 48m</small></div><ShieldCheck/></div></header>
  <section className="metrics"><Metric icon={<Activity/>} label="运行实例" value={`${running} / ${instances.length}`} note="所有节点稳定"/><Metric icon={<Users/>} label="在线玩家" value={String(instances.reduce((n,x)=>n+x.players,0))} note="跨全部实例"/><Metric icon={<Database/>} label="内容存储" value="42.8 GB" note="可用 81%"/><Metric icon={<RefreshCw/>} label="进行中作业" value="1" note="游戏文件校验 · 64%"/></section>
  <section className="work"><div className="section-head"><div><p className="eyebrow">INSTANCE GRID</p><h2>游戏实例</h2></div><button className="create"><Plus/>创建实例</button></div><div className="grid">{instances.map(x=><article className={`card ${x.actual_state}`} key={x.id}><div className="card-top"><span className="status"><i></i>{x.actual_state==='running'?'运行中':'已停止'}</span><button className="icon-btn" aria-label={`查看 ${x.name}`}><ChevronRight/></button></div><h3>{x.name}</h3><p className="endpoint">LOCAL-01 : {x.game_port}</p><div className="map"><Map/><span><small>当前地图</small><b>{x.start_map}</b></span><em>{x.game_mode.toUpperCase()}</em></div><div className="stats"><span><small>玩家</small><b>{x.players} / {x.max_players}</b></span><span><small>CPU</small><b>{x.cpu}%</b></span><span><small>内存</small><b>{x.memory} GB</b></span></div><div className="bar"><i style={{width:`${Math.max(x.cpu,2)}%`}}/></div><div className="actions">{x.actual_state==='running'?<button aria-label={`停止 ${x.name}`} onClick={()=>setPending(x)}><CircleStop/>停止</button>:<button onClick={()=>onAction(x.id,'start')}><Play/>启动</button>}<button><TerminalSquare/>控制台</button></div></article>)}</div></section>
  <section className="activity"><div><p className="eyebrow">LIVE JOB</p><h2>游戏文件校验</h2><p>专家写实 · SteamCMD App 222860</p></div><strong>64%</strong><div className="jobbar"><i/></div><small>阶段 2 / 4 · 校验游戏文件 · 已运行 03:42</small></section>
  </main>{pending&&<div className="modal-wrap"><div className="modal" role="dialog" aria-modal="true" aria-labelledby="confirm-title"><span className="danger-icon"><CircleStop/></span><p className="eyebrow">DESTRUCTIVE ACTION</p><h2 id="confirm-title">停止 {pending.name}？</h2><p>服务器将先通过原生控制台执行 quit，再进入 Docker 宽限停止。在线玩家会断开连接。</p><div><button onClick={()=>setPending(null)}>取消</button><button className="danger" aria-label="确认停止" onClick={()=>{onAction(pending.id,'stop');setPending(null)}}>确认停止</button></div></div></div>}</div>}
function Metric({icon,label,value,note}:{icon:React.ReactNode;label:string;value:string;note:string}){return <article className="metric"><span>{icon}</span><div><small>{label}</small><b>{value}</b><em>{note}</em></div></article>}
