import { fireEvent, render, screen, waitFor } from '@testing-library/react';
import { describe,it,expect,vi } from 'vitest';
import { GameLogsPage, truncateForDisplay, DISPLAY_PREVIEW_LIMIT } from './GameLogsPage';
it('truncateForDisplay keeps only the display tail',()=>{const result=truncateForDisplay('a'.repeat(DISPLAY_PREVIEW_LIMIT+5));expect(result.truncated).toBe(true);expect(result.text).toHaveLength(DISPLAY_PREVIEW_LIMIT)});
describe('GameLogsPage',()=>{ it('loads tree and preview metadata',async()=>{ const api=vi.fn().mockResolvedValueOnce({entries:[{path:'game/a.log',kind:'file',size:12,modified_at:'now'}]}).mockResolvedValueOnce({text:'INFO hi',size:8,modified_at:'now',truncated:false}); render(<GameLogsPage instanceID="i1" api={api}/>); await waitFor(()=>expect(screen.getByText('game/a.log')).toBeTruthy()); expect(api).toHaveBeenCalled(); }); });
it('renders nested directories collapsed then expands',async()=>{const api=vi.fn().mockResolvedValue({entries:[{path:'game/logs',kind:'directory'},{path:'game/logs/a',kind:'directory'},{path:'game/logs/a/x.log',kind:'file'}]});render(<GameLogsPage instanceID="i" api={api}/>);await waitFor(()=>expect(screen.getByRole('heading',{name:'game'})).toBeTruthy());const logs=await waitFor(()=>screen.getByLabelText('Toggle game/logs'));expect(screen.queryByText('game/logs/a/x.log')).toBeNull();fireEvent.click(logs);const nested=await waitFor(()=>screen.getByLabelText('Toggle game/logs/a'));fireEvent.click(nested);await waitFor(()=>expect(screen.getByText('game/logs/a/x.log')).toBeTruthy())});
it('uses sourcemod kind in download',async()=>{const api=vi.fn().mockResolvedValueOnce({entries:[{path:'sourcemod/a.log',kind:'file'}]}).mockResolvedValueOnce({text:'x'});render(<GameLogsPage instanceID="i" api={api}/>);await waitFor(()=>screen.getByLabelText('sourcemod/a.log').click());await waitFor(()=>expect(screen.getByLabelText('Download').getAttribute('href')).toContain('kind=sourcemod'))});
it('shows stable preview loading while retaining tree',async()=>{let resolve:any; const api=vi.fn().mockResolvedValueOnce({entries:[{path:'game/a.log',kind:'file'}]}).mockImplementationOnce(()=>new Promise(r=>resolve=r));render(<GameLogsPage instanceID="i" api={api}/>);await waitFor(()=>screen.getByLabelText('game/a.log'));fireEvent.click(screen.getByLabelText('game/a.log'));expect(screen.getByText('正在读取日志')).toBeTruthy();expect(screen.getByLabelText('game/a.log')).toBeTruthy();resolve({text:'x'});await waitFor(()=>expect(screen.queryByText('正在读取日志')).toBeNull())});
it('shows rotation on preview 404',async()=>{const api=vi.fn().mockResolvedValueOnce({entries:[{path:'game/a.log',kind:'file'}]}).mockRejectedValueOnce(new Error('404 not found'));render(<GameLogsPage instanceID="i" api={api}/>);await waitFor(()=>screen.getByLabelText('game/a.log'));fireEvent.click(screen.getByLabelText('game/a.log'));await waitFor(()=>expect(screen.getByText('Log rotated or deleted')).toBeTruthy())});
it('truncates oversized preview tail',()=>{const result=truncateForDisplay('a'.repeat(DISPLAY_PREVIEW_LIMIT+5));expect(result.truncated).toBe(true);expect(result.text).toHaveLength(DISPLAY_PREVIEW_LIMIT)});
it('shows server truncation提示',async()=>{const api=vi.fn().mockResolvedValueOnce({entries:[{path:'game/a.log',kind:'file'}]}).mockResolvedValueOnce({text:'tail',size:10*1024*1024+5,truncated:true});render(<GameLogsPage instanceID="i" api={api}/>);await waitFor(()=>screen.getByLabelText('game/a.log'));fireEvent.click(screen.getByLabelText('game/a.log'));await waitFor(()=>expect(screen.getByText(/Tail truncated/)).toBeTruthy())});

it('shows tree loading then empty state',async()=>{let resolve:any;const api=vi.fn().mockImplementationOnce(()=>new Promise(r=>resolve=r));render(<GameLogsPage instanceID="i" api={api}/>);expect(screen.getByText('Loading...')).toBeTruthy();resolve({entries:[]});await waitFor(()=>expect(screen.getByText('Empty')).toBeTruthy())});
it('shows tree error state',async()=>{const api=vi.fn().mockRejectedValueOnce(new Error('tree failed'));render(<GameLogsPage instanceID="i" api={api}/>);await waitFor(()=>expect(screen.getByRole('alert')).toHaveTextContent('tree failed'))});
it('shows non-404 preview errors',async()=>{const api=vi.fn().mockResolvedValueOnce({entries:[{path:'game/a.log',kind:'file'}]}).mockRejectedValueOnce(new Error('permission denied'));render(<GameLogsPage instanceID="i" api={api}/>);await waitFor(()=>screen.getByLabelText('game/a.log'));fireEvent.click(screen.getByLabelText('game/a.log'));await waitFor(()=>expect(screen.getByRole('alert')).toHaveTextContent('permission denied'));expect(screen.queryByText('Log rotated or deleted')).toBeNull()});
it('keeps only the latest preview when selections race',async()=>{let firstResolve:any,secondResolve:any;const api=vi.fn().mockResolvedValueOnce({entries:[{path:'game/a.log',kind:'file'},{path:'game/b.log',kind:'file'}]}).mockImplementationOnce(()=>new Promise(r=>firstResolve=r)).mockImplementationOnce(()=>new Promise(r=>secondResolve=r));render(<GameLogsPage instanceID="i" api={api}/>);await waitFor(()=>screen.getByLabelText('game/a.log'));fireEvent.click(screen.getByLabelText('game/a.log'));fireEvent.click(screen.getByLabelText('game/b.log'));secondResolve({text:'LATEST'});await waitFor(()=>expect(screen.getByText('LATEST')).toBeTruthy());firstResolve({text:'STALE'});await new Promise(r=>setTimeout(r,0));expect(screen.queryByText('STALE')).toBeNull()});




