import { fireEvent, render, screen, waitFor } from '@testing-library/react';
import { describe,it,expect,vi } from 'vitest';
import { GameLogsPage } from './GameLogsPage';
describe('GameLogsPage',()=>{ it('loads tree and preview metadata',async()=>{ const api=vi.fn().mockResolvedValueOnce({entries:[{path:'game/a.log',kind:'file',size:12,modified_at:'now'}]}).mockResolvedValueOnce({text:'INFO hi',size:8,modified_at:'now',truncated:false}); render(<GameLogsPage instanceID="i1" api={api}/>); await waitFor(()=>expect(screen.getByText('game/a.log')).toBeTruthy()); expect(api).toHaveBeenCalled(); }); });
it('renders nested directories collapsed then expands',async()=>{const api=vi.fn().mockResolvedValue({entries:[{path:'game/logs',kind:'directory'},{path:'game/logs/a',kind:'directory'},{path:'game/logs/a/x.log',kind:'file'}]});render(<GameLogsPage instanceID="i" api={api}/>);await waitFor(()=>expect(screen.getByRole('heading',{name:'game'})).toBeTruthy());const logs=await waitFor(()=>screen.getByLabelText('Toggle game/logs'));expect(screen.queryByText('game/logs/a/x.log')).toBeNull();fireEvent.click(logs);const nested=await waitFor(()=>screen.getByLabelText('Toggle game/logs/a'));fireEvent.click(nested);await waitFor(()=>expect(screen.getByText('game/logs/a/x.log')).toBeTruthy())});
it('uses sourcemod kind in download',async()=>{const api=vi.fn().mockResolvedValueOnce({entries:[{path:'sourcemod/a.log',kind:'file'}]}).mockResolvedValueOnce({text:'x'});render(<GameLogsPage instanceID="i" api={api}/>);await waitFor(()=>screen.getByLabelText('sourcemod/a.log').click());await waitFor(()=>expect(screen.getByLabelText('Download').getAttribute('href')).toContain('kind=sourcemod'))});
it('shows stable preview loading while retaining tree',async()=>{let resolve:any; const api=vi.fn().mockResolvedValueOnce({entries:[{path:'game/a.log',kind:'file'}]}).mockImplementationOnce(()=>new Promise(r=>resolve=r));render(<GameLogsPage instanceID="i" api={api}/>);await waitFor(()=>screen.getByLabelText('game/a.log'));fireEvent.click(screen.getByLabelText('game/a.log'));expect(screen.getByText('正在读取日志')).toBeTruthy();expect(screen.getByLabelText('game/a.log')).toBeTruthy();resolve({text:'x'});await waitFor(()=>expect(screen.queryByText('正在读取日志')).toBeNull())});
it('shows rotation on preview 404',async()=>{const api=vi.fn().mockResolvedValueOnce({entries:[{path:'game/a.log',kind:'file'}]}).mockRejectedValueOnce(new Error('404 not found'));render(<GameLogsPage instanceID="i" api={api}/>);await waitFor(()=>screen.getByLabelText('game/a.log'));fireEvent.click(screen.getByLabelText('game/a.log'));await waitFor(()=>expect(screen.getByText('Log rotated or deleted')).toBeTruthy())});
it('truncates oversized preview tail',async()=>{const api=vi.fn().mockResolvedValueOnce({entries:[{path:'game/a.log',kind:'file'}]}).mockResolvedValueOnce({text:'a'.repeat(10*1024*1024+5),size:10*1024*1024+5});render(<GameLogsPage instanceID="i" api={api}/>);await waitFor(()=>screen.getByLabelText('game/a.log'));fireEvent.click(screen.getByLabelText('game/a.log'));await waitFor(()=>expect(screen.getByText(/Tail truncated/)).toBeTruthy())});




